# Compiler
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17 -Iinclude

# Source and build setup
SRC = $(wildcard src/*.cpp) main.cpp
OBJ = $(patsubst %.cpp,build/%.o,$(notdir $(SRC)))
TARGET = main

# Build all object files
build: $(OBJ)

# Build target (main executable)
$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET) -mconsole

# Compile .cpp -> build/.o
build/%.o: src/%.cpp
	@mkdir -p build
	$(CXX) $(CXXFLAGS) -c $< -o $@

build/main.o: main.cpp
	@mkdir -p build
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean build files
clean:
	rm -f build/*.o $(TARGET) tests/*.o tests/*.exe tests/test*.exe

# Pattern rule for other tests (optional)
tests/test%: $(OBJ) tests/test%.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

TESTS := $(patsubst %.cpp,%,$(wildcard tests/*.cpp))

alltests: $(TESTS)