# Compiler
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17 -Iinclude

# Source and build setup
SRC = $(wildcard src/*.cpp) main.cpp
OBJ = $(SRC:.cpp=.o)
TARGET = main

# Build target
$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET)

# Compile .cpp -> .o
build/%.o: src/%.cpp
	@mkdir -p build
	$(CXX) $(CXXFLAGS) -c $< -o $@

build/main.o: main.cpp
	@mkdir -p build
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean build files
clean:
	rm -f build/*.o $(TARGET) tests/*.o tests/test*

# Test target (compiles all src/*.cpp + test file)
tests/test%: $(SRC) tests/test%.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@

TESTS := $(patsubst %.cpp,%,$(wildcard tests/*.cpp))

alltests: $(TESTS)